module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌹', '💉', '🩸', '💀', '🥀', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/BFalrJo3NQj0lq5F9GKvR5?mode=gi_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/3mv4wd.jpg', // Bloody Rose Image
    NEWSLETTER_JID: '120363406176407309@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: '🌹 ＢＬＯＯＤＹ ＲＯＳＥ 🌹',
    OWNER_NAME: 'ＬＯＲＤ ＩＮＤＵＭＩＮＡ 💉',
    OWNER_NUMBER: '94763003966',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ＢＬＯＯＤＹ ＲＯＳＥ ＢＯＴ 🥀',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBjdX81XquXcMfqXz2z',
};